### ISSUE TITLE
Snippet and auto id generation do not work as before

### ISSUE THREAD

**Issue by marcel-cw** [useblocks/sphinx-needs-vscode#33]
The snippet and auto id generation don't work as before. I am on a Windows machine and using the relative paths workaround from https://github.com/useblocks/sphinx-needs-vscode/issues/26 

**Snippet**

When I use the snippet functionality I get the following result:
```
.. req:: Dummy Title
   :id: NeedID
   :status: open

   Content.
```

With the old Sphinx-Needs package 1.2.2 in combination with the Esbonio language server, the snippet would be filled with an auto generated id. In the snippet above no _id_ is generated.

**Auto id generation**

When I use the auto id generation using the editor I get the following result:
`:id: 3f3b1468`

The generated id is missing the prefix that we have configured. With the Sphinx-Needs package 1.2.2 the result would have been `:id: REQ_3f3b1468` which is according to our sphinx-needs configuration in conf.py.

**Comment by NigNagNug** [comment]
+1, need a fix too.

**Comment by marcel-cw** [comment]
Thanks for the new release version 0.3.1! I retested the issue and works correctly now! 👍
